# Generated by Django 2.1.1 on 2019-07-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_customer_terms_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
