# Generated by Django 2.1.1 on 2019-08-07 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_auto_20190806_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
