# Generated by Django 2.1.1 on 2019-09-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_auto_20190807_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='random_id',
            field=models.CharField(default='xxxxxxxxxx', max_length=10),
        ),
    ]
